Add custom resources to collect

diff --git a/must-gather/gather_addon_resources b/must-gather/gather_addon_resources
--- a/must-gather/gather_addon_resources
+++ b/must-gather/gather_addon_resources
@@ -7,17 +7,20 @@ BASE_COLLECTION_PATH="${BASE_COLLECTION_PATH:-/must-gather}"
 mkdir -p $BASE_COLLECTION_PATH
 
 DEFAULT_NS=redhat-nvidia-gpu-addon
-ADDON_NAMESPACE=$(oc get subscriptions.operators.coreos.com --field-selector metadata.name=nvidia-gpu-addon-operator -A -ojsonpath={.items[].metadata.namespace} --ignore-not-found)
-if [[ -z "$ADDON_NAMESPACE" ]];
-then
-    echo "Warning: Addon namespace cannot be calculated, using '$DEFAULT_NS'" >&2
+ADDON_NAMESPACE=${ADDON_NAMESPACE:-$(oc get subscriptions.operators.coreos.com --field-selector metadata.name=nvidia-gpu-addon-operator -A -ojsonpath={.items[].metadata.namespace} --ignore-not-found)}
+if [[ -z "$ADDON_NAMESPACE" ]]; then
+    echo "Warning: Addon namespace cannot be determined as the subscription was not found, will collect from the default namespace '$DEFAULT_NS'" >&2
     ADDON_NAMESPACE=$DEFAULT_NS
 fi
 
-namespaces=(ns/$ADDON_NAMESPACE)
-oc adm inspect --dest-dir $BASE_COLLECTION_PATH --rotated-pod-logs "${namespaces[@]}"
+oc get ns $ADDON_NAMESPACE > /dev/null
+if [[ "$?" -ne 0 ]]; then
+  exit 1
+fi
 
-custom_resource_types=(catalogsources gpuaddons subscriptions)
+oc adm inspect --dest-dir $BASE_COLLECTION_PATH --rotated-pod-logs "ns/$ADDON_NAMESPACE"
+
+custom_resource_types=(catalogsource subscription operator gpuaddon nodefeaturediscovery consoleplugin prometheus alertmananger)
 filtered_custom_resource_types=()
 for ct in "${custom_resource_types[@]}"
 do
